Repository ghostty-org/ghostty, pull requests merged in 2025-05, with the labels that each got.

#7292 macOS: use file parent dir for `openTerminal` service cwd (#7286)
  macos/Sources/Features/Services/ServiceProvider.swift
Labels: os/macos

#7167 gtk: implement command palette
  po/com.mitchellh.ghostty.pot
  po/zh_CN.UTF-8.po
  src/apprt/gtk/App.zig
  src/apprt/gtk/CommandPalette.zig
  src/apprt/gtk/Window.zig
  src/apprt/gtk/gresource.zig
  src/apprt/gtk/style.css
  src/apprt/gtk/ui/1.0/menu-window-titlebar_menu.blp
  src/apprt/gtk/ui/1.5/command-palette.blp
  src/config/Config.zig
  src/input/Binding.zig
Labels: os/linux

#7083 gtk: implement global shortcuts
  src/apprt/gtk/App.zig
  src/apprt/gtk/GlobalShortcuts.zig
  src/apprt/gtk/key.zig
  src/config/Config.zig
Labels: os/linux

#7395 nix: don't strip if we are building a debug version of the package
  .github/workflows/test.yml
  nix/package.nix
Labels: packaging

#7408 Update Turkish translations
  po/tr_TR.UTF-8.po
Labels: translations

#7423 Add new and update Norwegian split translations
  po/nb_NO.UTF-8.po
Labels: translations

#7443 Add support for buffer switching with CSI ? 47 h/l
  src/terminal/modes.zig
  src/termio/stream_handler.zig
Labels: vt
