Repository ghostty-org/ghostty, pull requests merged in 2025-08, with the labels that each got.

#8123 apprt/gtk-ng: winproto behaviors (quick terminal, csd/ssd, blur, etc.)
  src/apprt/gtk-ng/class/application.zig
  src/apprt/gtk-ng/class/surface.zig
  src/apprt/gtk-ng/class/window.zig
  src/apprt/gtk-ng/css/style.css
  src/apprt/gtk-ng/ext.zig
  src/apprt/gtk-ng/ui/1.5/window.blp
  src/apprt/gtk-ng/winproto.zig
  src/apprt/gtk-ng/winproto/noop.zig
  src/apprt/gtk-ng/winproto/wayland.zig
  src/apprt/gtk-ng/winproto/x11.zig
Labels: os/linux, gui

#8058 i18n: Updated translation for ko_KR
  po/ko_KR.UTF-8.po
Labels: translations

#8135 bash: upgrade to bash-preexec 0.6.0
  src/shell-integration/bash/bash-preexec.sh
Labels: shell-integration

#8126 Added and updated translations for id_ID
  po/id_ID.UTF-8.po
Labels: translations

#8151 update Polish translations
  po/pl_PL.UTF-8.po
Labels: translations

#8157 gtk-ng: a couple of minor fixes
  src/apprt/gtk-ng/class/surface.zig
  src/apprt/gtk-ng/ui/1.2/surface.blp
Labels: os/linux, gui

#8202 apprt/gtk-ng: create/close split functionality
  src/apprt/gtk-ng/build/gresource.zig
  src/apprt/gtk-ng/class/application.zig
  src/apprt/gtk-ng/class/close_confirmation_dialog.zig
  src/apprt/gtk-ng/class/split_tree.zig
  src/apprt/gtk-ng/class/tab.zig
  src/apprt/gtk-ng/class/window.zig
  src/apprt/gtk-ng/css/style-dark.css
  src/apprt/gtk-ng/css/style.css
  src/apprt/gtk-ng/ui/1.2/surface.blp
  src/apprt/gtk-ng/ui/1.5/split-tree-split.blp
  src/apprt/gtk-ng/ui/1.5/tab.blp
  src/datastruct/split_tree.zig
  valgrind.supp
Labels: os/linux, gui

#8182 gtk-ng: don't use signals to toggle command palette
  build.zig.zon
  build.zig.zon.json
  build.zig.zon.nix
  build.zig.zon.txt
  flatpak/zig-packages.json
  src/apprt/gtk-ng/class/application.zig
  src/apprt/gtk-ng/class/command_palette.zig
  src/apprt/gtk-ng/class/split_tree.zig
  src/apprt/gtk-ng/class/surface.zig
  src/apprt/gtk-ng/class/window.zig
  src/apprt/gtk-ng/ui/1.5/command-palette.blp
  src/apprt/gtk-ng/weak_ref.zig
Labels: os/linux, gui

#8265 deps: update z2d to 0.7.1 tagged release
  build.zig.zon
  build.zig.zon.json
  build.zig.zon.nix
  build.zig.zon.txt
  flatpak/zig-packages.json
  src/font/sprite/testdata/U+1FB00...U+1FBFF-12x24+3.png
  src/font/sprite/testdata/U+1FB00...U+1FBFF-18x36+4.png
  src/font/sprite/testdata/U+1FB00...U+1FBFF-9x17+1.png
  src/font/sprite/testdata/U+E000...U+E0FF-12x24+3.png
  src/font/sprite/testdata/U+E000...U+E0FF-18x36+4.png
Labels: dependencies

#8281 zsh: minor shell integration improvements
  src/shell-integration/zsh/.zshenv
  src/termio/shell_integration.zig
Labels: shell-integration

#8230 macOS Custom Icon + Persistence
  macos/Sources/App/macOS/AppDelegate.swift
  macos/Sources/Ghostty/Ghostty.Config.swift
  macos/Sources/Ghostty/Package.swift
  src/config/Config.zig
Labels: os/macos, gui

#8114 macOS: Add macos-dock-drop-folder-behavior (new tab or window) configuration option
  macos/Sources/App/macOS/AppDelegate.swift
  macos/Sources/Ghostty/Ghostty.Config.swift
  src/config/Config.zig
  src/config/formatter.zig
Labels: os/macos, gui

#8306 gtk-ng: add a helper to reduce boilerplate in GTK IPC
  src/apprt/gtk-ng/ipc/DBus.zig
  src/apprt/gtk-ng/ipc/new_window.zig
Labels: os/linux, gui

#8082 cli: add filtering hotkey to list_themes
  src/cli/list_themes.zig
Labels: cli

#8347 i18n: add missing es_AR translations
  po/es_AR.UTF-8.po
Labels: translations

#8363 Close other tabs feature on Mac.
  include/ghostty.h
  macos/Sources/App/macOS/MainMenu.xib
  macos/Sources/Features/Terminal/TerminalController.swift
  macos/Sources/Ghostty/Ghostty.App.swift
  macos/Sources/Ghostty/Package.swift
  src/Surface.zig
  src/apprt/action.zig
  src/apprt/gtk-ng/class/application.zig
  src/apprt/gtk-ng/class/command_palette.zig
  src/apprt/gtk/App.zig
  src/apprt/gtk/CommandPalette.zig
  src/input/Binding.zig
  src/input/command.zig
Labels: os/macos, gui

#8374 fix: update Spanish translations and revision date in es_BO.UTF-8.po
  po/es_BO.UTF-8.po
Labels: translations

#8371 i18n: Add missing ca_ES translations
  po/ca_ES.UTF-8.po
Labels: translations

#8376 gtk-ng: fix setting/unsetting of urgency
  src/apprt/gtk-ng/class/window.zig
  src/apprt/gtk-ng/ui/1.5/window.blp
Labels: os/linux, gui

#8392 Update macedonian translation strings
  po/mk_MK.UTF-8.po
Labels: translations

#8378 i18n: add new translations in fr_FR
  po/fr_FR.UTF-8.po
Labels: translations

#8379 i18n: update Ukrainian translation
  po/uk_UA.UTF-8.po
Labels: translations

#8093 macos: fix quick terminal fullscreen crash bug
  macos/Sources/Features/QuickTerminal/QuickTerminalController.swift
  macos/Sources/Helpers/Fullscreen.swift
Labels: os/macos, gui

#8122 fix: correct the cursor Y position value exposed to shader uniforms
  src/renderer/generic.zig
Labels: renderer
