Repository ghostty-org/ghostty, pull requests merged in 2025-03, with the labels that each got.

#6004 gtk: add localization support, take 3
  .github/workflows/test.yml
  CONTRIBUTING.md
  build.zig
  nix/devShell.nix
  nix/package.nix
  po/README_CONTRIBUTORS.md
  po/README_TRANSLATORS.md
  po/com.mitchellh.ghostty.pot
  po/zh_CN.UTF-8.po
  snap/snapcraft.yaml
  src/apprt/gtk/App.zig
  src/apprt/gtk/Surface.zig
  src/apprt/gtk/Window.zig
  src/apprt/gtk/i18n.zig
  src/build/GhosttyI18n.zig
  src/build/docker/debian/Dockerfile
  src/build/main.zig
  src/os/resourcesdir.zig
Labels: os/linux

#6090 gtk: implement quick terminal slide & autohide
  src/apprt/gtk/Window.zig
  src/apprt/gtk/winproto.zig
  src/apprt/gtk/winproto/noop.zig
  src/apprt/gtk/winproto/wayland.zig
  src/apprt/gtk/winproto/x11.zig
  src/build/SharedDeps.zig
  src/config/Config.zig
  src/input/Binding.zig
Labels: os/linux, gui

#5741 gtk: use AdwAlertDialog for close dialogs, fix incorrect close dialogs
  include/ghostty.h
  po/com.mitchellh.ghostty.pot
  po/zh_CN.UTF-8.po
  src/Surface.zig
  src/apprt/action.zig
  src/apprt/glfw.zig
  src/apprt/gtk/App.zig
  src/apprt/gtk/CloseDialog.zig
  src/apprt/gtk/Surface.zig
  src/apprt/gtk/Tab.zig
  src/apprt/gtk/TabView.zig
  src/apprt/gtk/Window.zig
  src/apprt/gtk/adwaita.zig
Labels: os/linux

#6601 translations: add German translation
  po/de_DE.UTF-8.po
  src/os/i18n.zig
  typos.toml
Labels: translations

#6658 termio, flatpak: implement process watcher with xev
  .github/workflows/test.yml
  src/os/flatpak.zig
  src/termio/Exec.zig
Labels: os/linux, packaging

#6787 gtk: convert App to zig-gobject
  build.zig.zon
  build.zig.zon.json
  build.zig.zon.nix
  build.zig.zon.txt
  src/apprt/gtk/App.zig
  src/apprt/gtk/Surface.zig
  src/apprt/gtk/Window.zig
  src/apprt/gtk/adwaita.zig
  src/apprt/gtk/c.zig
  src/apprt/gtk/cgroup.zig
  src/apprt/gtk/inspector.zig
  src/apprt/gtk/version.zig
Labels: os/linux

#6792 gtk: remove c.zig
  .github/workflows/test.yml
  po/com.mitchellh.ghostty.pot
  po/de_DE.UTF-8.po
  po/zh_CN.UTF-8.po
  src/apprt/gtk/App.zig
  src/apprt/gtk/ClipboardConfirmationWindow.zig
  src/apprt/gtk/ConfigErrorsDialog.zig
  src/apprt/gtk/ConfigErrorsWindow.zig
  src/apprt/gtk/ImguiWidget.zig
  src/apprt/gtk/View.zig
  src/apprt/gtk/c.zig
  src/apprt/gtk/gresource.zig
  src/apprt/gtk/inspector.zig
  src/apprt/gtk/key.zig
  src/apprt/gtk/ui/1.2/config-errors-dialog.blp
  src/apprt/gtk/ui/1.2/config-errors-dialog.ui
  src/apprt/gtk/ui/1.5/config-errors-dialog.blp
  src/apprt/gtk/version.zig
  src/cli/version.zig
Labels: os/linux

#6731 Add Norwegian Bokmål Translations
  CODEOWNERS
  po/nb_NO.UTF-8.po
  src/os/i18n.zig
Labels: translations

#5728 fix: inconsistent behavior from legacy and kitty Key encoding
  src/input/KeyEncoder.zig
Labels: input

#6771 pl_PL translations
  CODEOWNERS
  po/pl_PL.UTF-8.po
  src/os/i18n.zig
Labels: translations

#6885 fix canonicalizing some zh locales
  src/os/i18n.zig
Labels: translations
