Repository ghostty-org/ghostty, pull requests merged in 2025-09, with the labels that each got.

#8468 gtk-ng: pull in latest zig-gobject changes
  build.zig.zon
  build.zig.zon.json
  build.zig.zon.nix
  build.zig.zon.txt
  flatpak/zig-packages.json
Labels: dependencies, os/linux

#8512 Fix font handling for bitmap and non-sfnt fonts
  src/font/Collection.zig
  src/font/face/coretext.zig
  src/font/face/freetype.zig
Labels: font

#8022 Fix off-by-one error & adjust overline pos in cell height mod
  src/font/Metrics.zig
Labels: font

#8538 fix(terminal): move cursor left if VS15 makes cell narrow
  src/terminal/Terminal.zig
Labels: vt

#7074 i18n: add Italian translation
  CODEOWNERS
  po/it_IT.UTF-8.po
  src/os/i18n.zig
Labels: translations

#8633 Some portuguese translation updates
  po/pt_BR.UTF-8.po
Labels: translations

#8655 config: update theme names in docs
  src/config/Config.zig
Labels: documentation

#8819 Update README_TRANSLATORS to reflect the new i18n locales struct path
  po/README_TRANSLATORS.md
Labels: documentation

#8853 GTK: Fix split-divider-color
  src/apprt/gtk/class/application.zig
Labels: os/linux, gui

#8668 i18n: add Croatian hr_HR translation
  CODEOWNERS
  po/hr_HR.UTF-8.po
  src/os/i18n_locales.zig
Labels: translations

#8838 Workaround for #8669
  macos/Sources/Features/App Intents/NewTerminalIntent.swift
Labels: os/macos

#8927 feat: enable scaling mouse-scroll-multiplier for both precision and discrete scrolling
  src/Surface.zig
  src/cli/args.zig
  src/config.zig
  src/config/Config.zig
Labels: input
