Repository ghostty-org/ghostty, pull requests merged in 2025-02, with the labels that each got.

#5650 gtk(x11): set `WINDOWID` env var for subprocesses
  src/Surface.zig
  src/apprt/embedded.zig
  src/apprt/glfw.zig
  src/apprt/gtk/Surface.zig
  src/apprt/gtk/winproto.zig
  src/apprt/gtk/winproto/noop.zig
  src/apprt/gtk/winproto/wayland.zig
  src/apprt/gtk/winproto/x11.zig
  src/os/env.zig
  src/os/main.zig
  src/termio/Exec.zig
Labels: os/linux

#5644 Performable tab and split navigation
  include/ghostty.h
  macos/Sources/Ghostty/Ghostty.App.swift
  src/App.zig
  src/Surface.zig
  src/apprt/embedded.zig
  src/apprt/glfw.zig
  src/apprt/gtk/App.zig
  src/apprt/gtk/Surface.zig
  src/apprt/gtk/Window.zig
  src/apprt/gtk/notebook.zig
Labels: os/linux, input, feedback-requested

#5654 Improve GTK directional split movements
  src/apprt/gtk/Split.zig
Labels: os/linux

#3931 Added snap packaging
  .github/workflows/test.yml
  nix/devShell.nix
  snap/local/launcher
  snap/snapcraft.yaml
  src/apprt/gtk/Surface.zig
Labels: os/linux, packaging

#5807 [macOS] feat: Add "Split Left" and "Split Up" actions to menubar
  macos/Sources/App/macOS/AppDelegate.swift
  macos/Sources/App/macOS/MainMenu.xib
  macos/Sources/Features/Terminal/BaseTerminalController.swift
  macos/Sources/Ghostty/SurfaceView_AppKit.swift
Labels: os/macos

#5646 Equalize Splits invalid keybind
  src/config/Config.zig
Labels: input

#5777 Vertically center title when `macos-titlebar-style = tabs`
  macos/Sources/Features/Terminal/TerminalToolbar.swift
Labels: os/macos

#5837 gtk: fix closing window when last tab is closed
  src/apprt/gtk/TabView.zig
Labels: os/linux

#5404 gtk: apply all window appearance changes in syncAppearance
  src/apprt/gtk/Window.zig
  src/apprt/gtk/winproto.zig
  src/apprt/gtk/winproto/noop.zig
  src/apprt/gtk/winproto/wayland.zig
  src/apprt/gtk/winproto/x11.zig
  src/config/Config.zig
Labels: os/linux

#5897 Fix barely visible new tab button on macOS
  macos/Sources/Features/Terminal/TerminalController.swift
  macos/Sources/Features/Terminal/TerminalWindow.swift
Labels: os/macos

#5834 macOS: Fix new window focus when created from quick terminal
  macos/Sources/Features/Terminal/TerminalManager.swift
Labels: os/macos, feedback-requested

#5781 gtk: update menus to use popovers and builder ui files
  src/apprt/gtk/App.zig
  src/apprt/gtk/Builder.zig
  src/apprt/gtk/Surface.zig
  src/apprt/gtk/Tab.zig
  src/apprt/gtk/TabView.zig
  src/apprt/gtk/Window.zig
  src/apprt/gtk/gresource.zig
  src/apprt/gtk/menu.zig
  src/apprt/gtk/ui/menu-surface-context_menu.ui
  src/apprt/gtk/ui/menu-window-titlebar_menu.ui
  src/build/docker/debian/Dockerfile
Labels: os/linux

#5905 Gtk: change title prompt
  snap/snapcraft.yaml
  src/apprt/gtk/App.zig
  src/apprt/gtk/Builder.zig
  src/apprt/gtk/Surface.zig
  src/apprt/gtk/Window.zig
  src/apprt/gtk/blueprint_compiler.zig
  src/apprt/gtk/gresource.zig
  src/apprt/gtk/ui/prompt-title-dialog.blp
  src/build/SharedDeps.zig
  src/build/docker/debian/Dockerfile
  src/input/Binding.zig
Labels: os/linux

#5866 GTK: propagate config updates to the GTK apprt surfaces
  src/apprt/gtk/App.zig
  src/apprt/gtk/Surface.zig
  src/apprt/gtk/Window.zig
Labels: os/linux

#5941 gtk: update ResizeOverlay for zig-gobject
  src/apprt/gtk/ResizeOverlay.zig
  src/apprt/gtk/Surface.zig
Labels: os/linux

#5945 gtk: fix menu separator colors (again)
  src/apprt/gtk/style-dark.css
  src/apprt/gtk/style.css
Labels: os/linux

#5944 gtk: switch menus to use blueprints instead of raw builder ui
  src/apprt/gtk/Window.zig
  src/apprt/gtk/gresource.zig
  src/apprt/gtk/menu.zig
  src/apprt/gtk/ui/menu-surface-context_menu.blp
  src/apprt/gtk/ui/menu-surface-context_menu.ui
  src/apprt/gtk/ui/menu-window-titlebar_menu.blp
  src/apprt/gtk/ui/menu-window-titlebar_menu.ui
Labels: os/linux

#5954 gtk: ensure that the content scale is always positive
  src/apprt/gtk/Surface.zig
Labels: os/linux

#5955 fix(macos): prevent performing newTab shortcut on QuickTerminalWindow…
  macos/Sources/Features/QuickTerminal/QuickTerminalController.swift
  macos/Sources/Features/Terminal/TerminalManager.swift
Labels: os/macos

#5992 Fix elvish sudo integration and update documentation
  src/shell-integration/README.md
  src/shell-integration/elvish/lib/ghostty-integration.elv
Labels: shell-integration

#5968 gtk: switch clipboard confirmation to zig-gobject and blueprints
  src/apprt/gtk/Builder.zig
  src/apprt/gtk/ClipboardConfirmationWindow.zig
  src/apprt/gtk/Surface.zig
  src/apprt/gtk/blueprint_compiler.zig
  src/apprt/gtk/gresource.zig
  src/apprt/gtk/menu.zig
  src/apprt/gtk/ui/1.0/menu-surface-context_menu.blp
  src/apprt/gtk/ui/1.0/menu-window-titlebar_menu.blp
  src/apprt/gtk/ui/1.2/ccw-osc-52-read.blp
  src/apprt/gtk/ui/1.2/ccw-osc-52-read.ui
  src/apprt/gtk/ui/1.2/ccw-osc-52-write.blp
  src/apprt/gtk/ui/1.2/ccw-osc-52-write.ui
  src/apprt/gtk/ui/1.2/ccw-paste.blp
  src/apprt/gtk/ui/1.2/ccw-paste.ui
  src/apprt/gtk/ui/1.5/ccw-osc-52-read.blp
  src/apprt/gtk/ui/1.5/ccw-osc-52-write.blp
  src/apprt/gtk/ui/1.5/ccw-paste.blp
  src/apprt/gtk/ui/1.5/prompt-title-dialog.blp
  src/apprt/gtk/ui/README.md
  src/build/SharedDeps.zig
Labels: os/linux

#6008 fix(Metal): force a full rebuild in `setFontGrid`
  src/renderer/Metal.zig
Labels: os/macos

#5962 feat: respect maximize config on macOS
  macos/Sources/Features/Terminal/TerminalController.swift
  macos/Sources/Ghostty/Ghostty.Config.swift
Labels: os/macos

#6024 Fix Terminal Inspector option turns inactive if toggled in the Quick Terminal
  macos/Sources/Features/QuickTerminal/QuickTerminalController.swift
Labels: os/macos, gui
