Repository ghostty-org/ghostty, pull requests merged in 2025-06, with the labels that each got.

#7510 gtk/GlobalShortcuts: don't request session with no shortcuts
  src/apprt/gtk/GlobalShortcuts.zig
Labels: os/linux

#7515 gtk/TabView: do not closeTab within close-page signal handler
  src/apprt/gtk/TabView.zig
Labels: os/linux, gui

#7504 macOS: Add option to hide window buttons
  macos/Sources/Features/Terminal/TerminalController.swift
  macos/Sources/Features/Terminal/TerminalWindow.swift
  macos/Sources/Ghostty/Ghostty.Config.swift
  macos/Sources/Ghostty/Package.swift
  src/config/Config.zig
Labels: os/macos, gui

#7537 terminal: fix crash when reflowing grapheme with a spacer head
  src/terminal/PageList.zig
  src/terminal/page.zig
Labels: vt

#7535 macOS: Undo/Redo for changes to windows, tabs, and splits
  include/ghostty.h
  macos/Ghostty.xcodeproj/project.pbxproj
  macos/Sources/App/macOS/AppDelegate.swift
  macos/Sources/App/macOS/MainMenu.xib
  macos/Sources/Features/QuickTerminal/QuickTerminalController.swift
  macos/Sources/Features/Services/ServiceProvider.swift
  macos/Sources/Features/Splits/SplitTree.swift
  macos/Sources/Features/Terminal/BaseTerminalController.swift
  macos/Sources/Features/Terminal/TerminalController.swift
  macos/Sources/Features/Terminal/TerminalManager.swift
  macos/Sources/Features/Terminal/TerminalRestorable.swift
  macos/Sources/Ghostty/Ghostty.App.swift
  macos/Sources/Ghostty/Ghostty.Config.swift
  macos/Sources/Ghostty/SurfaceView.swift
  macos/Sources/Ghostty/SurfaceView_AppKit.swift
  macos/Sources/Helpers/ExpiringUndoManager.swift
  macos/Sources/Helpers/Extensions/Duration+Extension.swift
  macos/Sources/Helpers/Extensions/NSApplication+Extension.swift
  macos/Sources/Helpers/Extensions/UndoManager+Extension.swift
  src/App.zig
  src/Surface.zig
  src/apprt/action.zig
  src/apprt/embedded.zig
  src/apprt/glfw.zig
  src/apprt/gtk/App.zig
  src/build/mdgen/mdgen.zig
  src/config/Config.zig
  src/input/Binding.zig
  src/input/command.zig
Labels: os/macos, gui

#7547 macos: add id to SplitTreeView to detect tree structural changes
  macos/Sources/Features/Splits/SplitTree.swift
  macos/Sources/Features/Splits/TerminalSplitTreeView.swift
Labels: os/macos, gui

#7594 macos: menu item symbols for Tahoe
  macos/Ghostty.xcodeproj/project.pbxproj
  macos/Sources/App/macOS/AppDelegate.swift
  macos/Sources/App/macOS/MainMenu.xib
  macos/Sources/Ghostty/SurfaceView_AppKit.swift
  macos/Sources/Helpers/Extensions/NSMenuItem+Extension.swift
Labels: os/macos

#7611 bash: remove dependency on $GHOSTTY_RESOURCES_DIR
  src/shell-integration/bash/ghostty.bash
Labels: shell-integration

#7634 macOS: App Intents
  .github/workflows/test.yml
  README.md
  include/ghostty.h
  macos/Ghostty.xcodeproj/project.pbxproj
  macos/Sources/App/macOS/AppDelegate.swift
  macos/Sources/Features/App Intents/CloseTerminalIntent.swift
  macos/Sources/Features/App Intents/CommandPaletteIntent.swift
  macos/Sources/Features/App Intents/Entities/CommandEntity.swift
  macos/Sources/Features/App Intents/Entities/TerminalEntity.swift
  macos/Sources/Features/App Intents/GetTerminalDetailsIntent.swift
  macos/Sources/Features/App Intents/GhosttyIntentError.swift
  macos/Sources/Features/App Intents/InputIntent.swift
  macos/Sources/Features/App Intents/IntentPermission.swift
  macos/Sources/Features/App Intents/KeybindIntent.swift
  macos/Sources/Features/App Intents/NewTerminalIntent.swift
  macos/Sources/Features/App Intents/QuickTerminalIntent.swift
  macos/Sources/Features/Command Palette/TerminalCommandPalette.swift
  macos/Sources/Features/QuickTerminal/QuickTerminalController.swift
  macos/Sources/Features/Terminal/BaseTerminalController.swift
  macos/Sources/Features/Terminal/TerminalController.swift
  macos/Sources/Ghostty/AppError.swift
  macos/Sources/Ghostty/Ghostty.Command.swift
  macos/Sources/Ghostty/Ghostty.Config.swift
  macos/Sources/Ghostty/Ghostty.Error.swift
  macos/Sources/Ghostty/Ghostty.Input.swift
  macos/Sources/Ghostty/Ghostty.Surface.swift
  macos/Sources/Ghostty/InspectorView.swift
  macos/Sources/Ghostty/Package.swift
  macos/Sources/Ghostty/SurfaceView.swift
  macos/Sources/Ghostty/SurfaceView_AppKit.swift
  macos/Sources/Ghostty/SurfaceView_UIKit.swift
  macos/Sources/Helpers/Extensions/Array+Extension.swift
  macos/Sources/Helpers/Extensions/NSView+Extension.swift
  macos/Sources/Helpers/Extensions/Optional+Extension.swift
  macos/Sources/Helpers/PermissionRequest.swift
  src/apprt/embedded.zig
  src/config/Config.zig
Labels: os/macos

#7632 feat(translation): add missing pt_BR translation
  po/pt_BR.UTF-8.po
Labels: translations

#7653 docs: document uniforms available to custom shaders
  src/config/Config.zig
  src/renderer/generic.zig
Labels: documentation

#7029 pwd: fix hostname resolution on macos
  src/os/hostname.zig
  src/termio/stream_handler.zig
Labels: os/macos

#7657 fix: always wait on open command to avoid defunct processes
  src/os/open.zig
Labels: os/linux

#7679 dbus and systemd activation - take 2
  dist/linux/app.desktop.in
  dist/linux/com.mitchellh.ghostty.metainfo.xml.in
  dist/linux/dbus.service.flatpak.in
  dist/linux/dbus.service.in
  dist/linux/systemd.service.in
  flatpak/com.mitchellh.ghostty-debug.yml
  src/apprt/gtk/App.zig
  src/apprt/gtk/Surface.zig
  src/build/Config.zig
  src/build/GhosttyResources.zig
  src/config/Config.zig
Labels: os/linux

#5590 gtk: add option to always display the tab bar
  src/apprt/gtk/Window.zig
  src/config/Config.zig
Labels: os/linux, gui, feedback-requested

#6706 deps: Default gtk4-layer-shell system integration to true
  snap/snapcraft.yaml
  src/build/Config.zig
  src/build/SharedDeps.zig
Labels: os/linux

#7710 Equalize splits based on children oriented in the same direction
  macos/Sources/Features/Splits/SplitTree.swift
Labels: os/macos, gui

#6783 gtk: add "remember choice" toggle for clipboard confirmation dialog
  po/com.mitchellh.ghostty.pot
  po/zh_CN.UTF-8.po
  src/apprt/gtk/ClipboardConfirmationWindow.zig
  src/apprt/gtk/adw_version.zig
  src/apprt/gtk/style.css
  src/apprt/gtk/ui/1.5/ccw-osc-52-read.blp
  src/apprt/gtk/ui/1.5/ccw-osc-52-write.blp
Labels: os/linux

#7397 Add Argentinian Spanish translation and locale support
  CODEOWNERS
  po/es_AR.UTF-8.po
  src/os/i18n.zig
Labels: translations

#7725 termio: indicate support for OSC 52 in primary DA report
  src/termio/Termio.zig
  src/termio/stream_handler.zig
Labels: vt
